steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-prediction-linearregression-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-prediction-linearregression-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ml-prediction-linearregression-app'
      - '--image=gcr.io/$PROJECT_ID/ml-prediction-linearregression-app'
      - '--region=us-east1'

images:
  - 'gcr.io/$PROECT_ID/ml-prediction-linearregression-app'

